baseline:
  vocab_size: 16
  seq_len: 128
  num_train_examples: 12800
  multi_query: True
  k_motif_size: 3
  v_motif_size: 3

changes:
  vocab_size: [32, 64]
  seq_len: [512]
  num_train_examples: [6400]